### ISSUE TITLE
Age restriction page

### ISSUE THREAD

**Issue by lunfman** [lunfman/HotMiamiWeb#7]
Age restriction page design with form in the center.

- [x] create new html file (you can use sample from scripts/ager/age.html)
- [x] use css and html from home page to create a hero image also know as full screen image as background.
- [x] align form to the center(in every direction)
- [x] make it responsive
- [x] apply css to form to make it pretty 
- [x] integrate with  script for age validation (location scripts/ager or write own script)
- [x] Add new feature to the script (if user did not pass age validation redirect to access denied page)

**Comment by andreikuznetsov-ut** [comment]
Done!
